[workspace]
members = [
  "zomes/contacts/integrity",
  "zomes/contacts/coordinator",
  "zomes/contacts/types/integrity_types",
  "zomes/contacts/types/coordinator_types",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
