[workspace]
members = [
  "zome/zomes/contacts/integrity",
  "zome/zomes/contacts/coordinator",
  "zome/zomes/contacts/types/integrity_types",
  "zome/zomes/contacts/types/coordinator_types"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
